### ISSUE TITLE
Segfault in Windows tests

### ISSUE THREAD

**Issue by gruenich** [xiaoyeli/superlu#134] opened 2023-12-01 21:51 UTC
While adding the Windows runner, we found out that the tests are segfaulting using MSVC. #133 contains a more detailed analysis of the issue. Valgrind can also detect it on Linux.

Without this fix, we cannot enable the tests on Windows and the Windows runner is only testing configure and building.

**Comment by wo80** [comment] 2023-12-02 09:07
Due to the lack of communication, I'm still not sure if @xiaoyeli  has gotten the point that this is **not a problem with Windows**. It's a problem with the tests passing on Linux and Mac, though there is clearly something going wrong.

Let me add some more thoughts to my analysis in https://github.com/xiaoyeli/superlu/pull/133#issuecomment-1826879216.  I think there are two possibilities:

1) The value of -1 for `urow` is invalid. This would mean that the error has to be fixed in the SuperLU code.
2) The (at least to me) more plausible possibility is that the value is valid and it's an indicator for "stop processing, no more data to come here, the matrix was singular". This raises a few questions:
   - When was this "feature" introduced? Is it properly documented? The code in dgst01 (and its siblings) might be used by users of SuperLU, so it aught to be documented!
   - Is dgst01 supposed to work for singular matrices at all? If it is, why does it not check for that value?
   - Why do the tests pass on Linux and Mac?

The answer to that last question is easy: the tests are way too complex. Ideally, if a test fails, it would give a hint about what goes wrong. The tests as they are now, have four nested `for` loops (`imat`, `iequed`, `ifact` and `equil`), but only one indicator for failure (`nfails`). This is absolutly useless when it comes to help finding the cause of a test failure. You have to debug the tests (which is not what tests are made for).

One way to improve this would be to add more output. This will then at least give a hint at what stage the error occurred (in particular in case of a segfault). Maybe add an additional command line option _-v_ to enable more verbose output.

**Comment by xiaoyeli** [comment] 2023-12-04 05:27
I'll use valgrind to fix the testers. I merged [https://github.com/xiaoyeli/superlu/pull/133](url) to temporarily not run testers on Windows

**Comment by xiaoyeli** [comment] 2023-12-31 17:35
@wo80 @gruenich  I finally got around to fix this. It's related to testing code error while testing singular matrices. Thanks for your detailed report.

**Comment by wo80** [comment] 2023-12-31 17:49
Thanks @xiaoyeli. All tests are passing now. I suggest you undo https://github.com/xiaoyeli/superlu/pull/133/commits/0559d56084de64c7d2384e49165f79b2fd0a601f , so that all platforms are tested properly.

**Comment by wo80** [comment] 2024-01-01 11:05
It might be worth also updating the _(c|d|s|z)gst01.c_ files:
https://github.com/xiaoyeli/superlu/blob/c173a6642c1dbb726c58777145396be3b194c747/TESTING/cgst01.c#L38-L40
Looking at the changes in c173a6642c1dbb726c58777145396be3b194c747, it seems _n_ is not the number of columns but rather the rank of _A_.

In any case, I think that the method should use `exit(-1)` or at least print an error message in case `urow` is invalid. As we have seen, Linux and Mac did not report any problem, so checking this explicitly would be a good idea. Maybe it's also worth opening a separate issue for this (a general review/cleanup of the tests).

**Closed** 2024-01-08 17:45 UTC
